name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint & Typecheck
        run: npm run check

      - name: Build all (packages + app)
        run: npm run build:all

      - name: Upload Next build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: apps/web/.next
